version: '3'
services:
  php:
    image: yiisoftware/yii2-php:7.4-fpm
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    links:
      - postgresql
    networks:
      backend:
        ipv4_address: 192.168.10.2

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.yii2.conf:/etc/nginx/conf.d/yii2.conf
    ports:
      - "80:80"
    restart: always
    networks:
      - backend

  postgresql:
    image: postgres:12-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: yii2
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: yii2
    ports:
      - "5432:5432"
    restart: always
    networks:
      backend:
        ipv4_address: 192.168.10.3

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/16
          gateway: 192.168.10.1