version: '3'
services:
  php:
    image: yiisoftware/yii2-php:7.4-fpm
    depends_on:
      postgresql:
        condition: service_healthy
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.yii2.conf:/etc/nginx/conf.d/yii2.conf
    ports:
      - "80:80"
    restart: always

  postgresql:
    image: postgres:12-alpine
    volumes:
    - ./fixtures.sql:/docker-entrypoint-initdb.d/fixtures.sql
    # Нужно, что бы постгрес успел сгенерировать фикстуры
    healthcheck:
      test: "exit 0"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: test
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: maindb
    ports:
      - "5432:5432"
    restart: always